target_name: "SalePrice"

remove_out_train: True

remove_out_valid: True

remove_out_test: False

alpha: 0.2

max_evals: 15

params_hgb: {
    "max_iter": 1000,
    "max_depth": 7,
    "feat_cat": [
        'MSSubClass', 'MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
        'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
        'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd',
        'MasVnrType', 'Foundation',
        'Heating', 'CentralAir', 'Electrical', 'Functional', 'GarageType', 'GarageFinish',
        'PavedDrive', 'MiscFeature', 'SaleType', 'SaleCondition',
    ]
}